mybatis:
  config-location: classpath:mybatisConfig/mybatis-config.xml
server:
  port: 9999
  servlet:
    context-path: /orderBOOTJPA
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      username: hr
      password: hr
      maximum-pool-size: 10
      minimum-idle: 2     
  mvc:
    view:
      prefix: /WEB-INF/views/
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org.hibernate: info 
    
